### PR TITLE
build: Restructure repo to have both front- and back-ends as separate workspaces

### PR DESCRIPTION
**Pull request by stanleyjones**
This PR essentially resets this repository to have two separate NPM workspaces, for `client` and `server`. In `client`, we have a basic Create React App framework, slightly modified to be more on par with our other apps (e.g. Alberto, Gwen). In `server` we have a basic NestJS framework, again slightly modified to serve the front-end.

**BEFORE**
```
├── LICENSE
├── README.md
├── commitlint.config.js
├── index.html
├── netlify.toml
├── package-lock.json
├── package.json
├── public
│   └── assets
├── src
│   ├── App.tsx
│   ├── demodata
│   ├── index.tsx
│   ├── lib
│   ├── mocks
│   └── setup.tsx
├── tsconfig.json
├── vercel.json
├── vite.config.ts
├── vitest.config.ts
└── yarn.lock
```

**AFTER**
```
├── Procfile
├── client
│   ├── README.md
│   ├── config-overrides.js
│   ├── package.json
│   ├── public
│   ├── src
│   └── tsconfig.json
├── package-lock.json
├── package.json
└── server
    ├── README.md
    ├── nest-cli.json
    ├── package.json
    ├── src
    ├── test
    ├── tsconfig.build.json
    └── tsconfig.json
```

### CODE REVIEW

**Review by hansl — APPROVED** [review]
Approved but is CI okay?

**Comment by stanleyjones** [comment]
Investigating CI.

**Comment by stanleyjones** [comment]
Circle is passing. It's Netlify that's failing, which makes sense and is fine since we're moving to Heroku anyway. I paused CD in Netlify for now.

**Comment by hansl** [comment]
Do you need me to merge?

**Pull request merged**
